name = input("Enter your name: ")
age = input('Enter your age: ')
gender = input("Enter your gender: ")
state = input("Enter your state: ")
lga = input("Enter your lga: ")
religion = input("Enter your religion: ")
sex = input("Enter your sex: ")
occupation = input('Enter your occupation: ')
hobbies = input("Enter your hobbies: ")

#output
print(name)
print(age)
print(gender)
print(state)
print(lga)
print(religion)
print(sex)
print(occupation)
print(hobbies)
